### ISSUE TITLE
HW 3 - Building a web application w/ Node & Express

### ISSUE THREAD

**Issue by thavythach** [UPS-CSCI240-S17/ThavyThach#1]
Overview
This assignment simply continues where the last one left off. You will use the same Github repository and Heroku application as for Homework 2, simply committing and pushing the new changes to both remotes.

Following the instructions in Chapter 4 of Getting MEAN, you'll begin to build a static website using Node.js and Express.js. Node.js is a platform for running JavaScript outside of a browser (i.e. on a server). Express.js is a server-side framework written in JavaScript (and executed on Node.js) that handles the work of a web server in a flexible and extensible way.

For this assignment, you will implement the application through the end of Chapter 4. To do this, you will also need to find and correct the typo in Chapter 4. There is a typo in Chapter 4 that will break the whole application if not corrected. You should find and identify the typo, and mention it in the Readme.md file of your repository. The book's support files are available on Github, so you can compare what you find in the book with the working files to find the bug.

Chapter notes
Read the chapter notes in my project repository for details on what is required for this chapter and important tips for working through the chapter.

Jade and HTML

This assignment also involves using the Jade templating framework for writing web page templates. Jade lets you write web page content in a simpler, easier-to-read way than HTML, and enables you to create general layouts that can be populated by data using variables, all of which is later converted to HTML "behind the scenes" for the browser. Jade is not part of the standard Mean.js boilerplate, so probably won't be using it in your group project, but it's a great tool to get familiar with.

Although it's very convenient, knowing Jade is not a substitute for knowing HTML. You should keep this in mind and be aware that there is always a one-to-one correspondence between Jade code and the HTML it converts to.

By the way, Jade is not the only alternate markup language that can be used to generate HTML. An even simpler (albeit less powerful) one is Markdown, which is supported by Github. This is why the Readme file uses the .md suffix. (You could use .txt or .html, but you would lose the benefits of Markdown.)

**Comment by tonymullen** [comment]
Everything okay? GitHub issues are a way to report bugs or possibly request functionality. Any of us in the group can comment and close the issue if we think it's resolved.

**Comment by thavythach** [comment]
@tonymullen this is going to be a log of my commits throughout the chapter. I do a specific way of committing aka:

      git commit -m "(#1) some random commit comment"

where (#1) <-- tags commits to the issue where I can track everything nicely and see all the code at different commit times.
